// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat.proto
// Protobuf Java Version: 4.29.3

package chat;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Sender's ID
   * </pre>
   *
   * <code>string from_id = 1;</code>
   * @return The fromId.
   */
  java.lang.String getFromId();
  /**
   * <pre>
   * Sender's ID
   * </pre>
   *
   * <code>string from_id = 1;</code>
   * @return The bytes for fromId.
   */
  com.google.protobuf.ByteString
      getFromIdBytes();

  /**
   * <pre>
   * Recipient's ID
   * </pre>
   *
   * <code>string to_id = 2;</code>
   * @return The toId.
   */
  java.lang.String getToId();
  /**
   * <pre>
   * Recipient's ID
   * </pre>
   *
   * <code>string to_id = 2;</code>
   * @return The bytes for toId.
   */
  com.google.protobuf.ByteString
      getToIdBytes();

  /**
   * <pre>
   * Message text
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * Message text
   * </pre>
   *
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * Timestamp
   * </pre>
   *
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
