// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat.proto
// Protobuf Java Version: 4.29.3

package chat;

public final class Chat {
  private Chat() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Chat.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_ReceiveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_ReceiveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chat_SendResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\004chat\"N\n\013ChatMessage\022\017\n\007fro" +
      "m_id\030\001 \001(\t\022\r\n\005to_id\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\022" +
      "\021\n\ttimestamp\030\004 \001(\003\"#\n\016ReceiveRequest\022\021\n\t" +
      "client_id\030\001 \001(\t\"\037\n\014SendResponse\022\017\n\007succe" +
      "ss\030\001 \001(\0102\201\001\n\013ChatService\0224\n\013SendMessage\022" +
      "\021.chat.ChatMessage\032\022.chat.SendResponse\022<" +
      "\n\017ReceiveMessages\022\024.chat.ReceiveRequest\032" +
      "\021.chat.ChatMessage0\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_ChatMessage_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Text", "Timestamp", });
    internal_static_chat_ReceiveRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_ReceiveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_ReceiveRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_chat_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chat_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chat_SendResponse_descriptor,
        new java.lang.String[] { "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
