// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chat.proto
// Protobuf Java Version: 4.29.3

package chat;

public interface ReceiveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.ReceiveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Client's ID to receive messages for
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Client's ID to receive messages for
   * </pre>
   *
   * <code>string client_id = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
